name = "Fast Pack"
author = "Hokusai"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe80d4c9eaceaa9eaa4febad9f196e91eb36341ab590d36fa06e4d9f11cc4420"

[versions]
fabric = "0.17.2"
minecraft = "1.21.9"
